export const currencyList = [
    { name: "دولار", code: "USD", locale: "en-US" },
    { name: "يورو", code: "EUR", locale: "de-DE" },
    { name: "جنيه إسترليني", code: "GBP", locale: "en-GB" },
    { name: "ين ياباني", code: "JPY", locale: "ja-JP" },
    { name: "دولار أسترالي", code: "AUD", locale: "en-AU" },
    { name: "دولار كندي", code: "CAD", locale: "en-CA" },
    { name: "فرنك سويسري", code: "CHF", locale: "de-CH" },
    { name: "يوان صيني", code: "CNY", locale: "zh-CN" },
    { name: "كرونا سويدية", code: "SEK", locale: "sv-SE" },
    { name: "دولار نيوزيلندي", code: "NZD", locale: "en-NZ" },
    { name: "بيزو مكسيكي", code: "MXN", locale: "es-MX" },
    { name: "دولار سنغافوري", code: "SGD", locale: "en-SG" },
    { name: "دولار هونج كونج", code: "HKD", locale: "en-HK" },
    { name: "كرونة نرويجية", code: "NOK", locale: "nb-NO" },
    { name: "وون كوري جنوبي", code: "KRW", locale: "ko-KR" },
    { name: "ليرة تركية", code: "TRY", locale: "tr-TR" },
    { name: "روبل روسي", code: "RUB", locale: "ru-RU" },
    { name: "روبية هندية", code: "INR", locale: "hi-IN" },
    { name: "ريال برازيلي", code: "BRL", locale: "pt-BR" },
    { name: "راند جنوب أفريقي", code: "ZAR", locale: "en-ZA" },
    { name: "كرونة دانماركية", code: "DKK", locale: "da-DK" },
    { name: "زلوتي بولندي", code: "PLN", locale: "pl-PL" },
    { name: "بات تايلندي", code: "THB", locale: "th-TH" },
    { name: "روبية إندونيسية", code: "IDR", locale: "id-ID" },
    { name: "رينغيت ماليزي", code: "MYR", locale: "ms-MY" },
    { name: "بيزو فلبيني", code: "PHP", locale: "tl-PH" },
    { name: "كرونة تشيكية", code: "CZK", locale: "cs-CZ" },
    { name: "فورنت مجري", code: "HUF", locale: "hu-HU" },
    { name: "شيكل إسرائيلي", code: "ILS", locale: "he-IL" },
    { name: "بيزو تشيلي", code: "CLP", locale: "es-CL" },
    { name: "بيزو كولومبي", code: "COP", locale: "es-CO" },
    { name: "ريال سعودي", code: "SAR", locale: "ar-SA" },
    { name: "درهم إماراتي", code: "AED", locale: "ar-AE" },
    { name: "ريال قطري", code: "QAR", locale: "ar-QA" },
    { name: "دينار كويتي", code: "KWD", locale: "ar-KW" },
    { name: "دينار أردني", code: "JOD", locale: "ar-JO" },
  ];
  